[package]
name = "mylib"
version = "0.1.0"
authors = ["Josh Chase <josh@prevoty.com>"]
edition = "2018"

[dependencies]
jni = "0.13.1"
opencv = "0.19.1"
openssl = "0.10"
hex = "0.3.2"

[lib]
crate_type = ["cdylib"]